### ISSUE TITLE
Pixel embedding picture from the original paper

### ISSUE THREAD

**Issue by zguo008** [MaybeShewill-CV/lanenet-lane-detection#154]
Hello, I am quite confused about the embedding branch in the original paper.

After a convolution layer and a de-convolution layer, there's a pixel embedding image(fig2 in the original paper).

I have a few questions:
1. In the code provided, there's a self.conv2d command corresponding to the pixel embedding process. Does it mean convolute with itself? or in other words, how can this pixel embedding achieved from the code provided?
2. How is the color seperation formed in the pixel embedding image(fig2 in the original paper)? 
3.How can i interpret from this pixel embedding image that different lanes will have it's own lane id?

Many thanks!!!

Best regards,

NG

**Comment by MaybeShewill-CV** [comment]
@zguo008 1.I do not know what you're talking about in the first question, please specify it. 2.The colors are seperated due to the instance loss function. The function will reduce the distance between the same
samples and enlarge the distance between the different samples. So the embedded feats will become similar if they belong to the same lane(as showed in the figure which will have similar color).
3. The feats of the pixels which belong different lanes will have large gap between(as showed in the figure they have different color). So after applying the cluster algorithm the cluster result will give you ids of each lane:)

**Comment by zguo008** [comment]
Thanks for the instant reply!

I found the pixel embedding function under lane_instance_segmentation.py under the function of compute loss. The command shows:  pix_embedding = self.conv2d(inputdata=decode_deconv, out_channel=3, kernel_size=1, use_bias=False, name='pix_embedding_conv')
            pix_embedding = self.relu(inputdata=pix_embedding, name='pix_embedding_relu')

I am not very sure why using self.conv2d?

Also regarding the pixel embedding image, as you have mentioned, lane pixels are cluster if they share a same color. But what I observe is that the color "stripe" not only covers the lane but also the background. Is the background filtered out before the clustering?

Best regards,

NG

**Comment by MaybeShewill-CV** [comment]
@zguo008 1.convolution op is used to generate the embedded feats of every pixel. 2.Background is also an kind of instance which will be calculated during the loss function:)
