### ISSUE TITLE
error ın test_lanenet

### ISSUE THREAD

**Issue by zeynep-dmrl** [MaybeShewill-CV/lanenet-lane-detection#480]
Hi!  I can't run test_lanenet.py. But I have an error.  In test_lanenet.py folder, this error is  " TypeError: Dimension value must be integer or None or have an __index__ method, got value '3.0' with type '<class 'float'>' ". I think  "ınput_tensor " variable cause error. ( input_tensor = tf.placeholder(dtype=tf.float32, shape=[1, 256, 512, 3], name='input_tensor') )
How I solve this problem? 

-----
Traceback (most recent call last):
  File "C:/Users/LENOVO/PycharmProjects/lanenet-lane-detection-master/tools/test_lanenet.py", line 164, in <module>
    test_lanenet('0.jpg',"lanenet-lane-detection-master/tusimple_lanenet")
  File "C:/Users/LENOVO/PycharmProjects/lanenet-lane-detection-master/tools/test_lanenet.py", line 94, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='LaneNet')
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\lanenet_model\lanenet.py", line 47, in inference
    extract_feats_result = self._frontend.build_model(
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\lanenet_model\lanenet_front_end.py", line 43, in build_model
    return self._net.build_model(
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\semantic_segmentation_zoo\bisenet_v2.py", line 1053, in build_model
    detail_branch_output = self.build_detail_branch(
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\semantic_segmentation_zoo\bisenet_v2.py", line 872, in build_detail_branch
    result = block_op(
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\semantic_segmentation_zoo\bisenet_v2.py", line 824, in _conv_block
    result = self.conv2d(
  File "C:\Users\LENOVO\PycharmProjects\lanenet-lane-detection-master\semantic_segmentation_zoo\cnn_basenet.py", line 72, in conv2d
    w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init)
-----

**Comment by MaybeShewill-CV** [comment]
@zeynep-dmrl Follow readme's instruction and check if you have used the right command:）

**Comment by sabih411** [comment]
@zeynep-dmrl I'm getting the same issue and can't figure out what exactly I did wrong.

**Comment by zeynep-dmrl** [comment]
@sabih411 I couldn't find solution for this issue

**Comment by imamim** [comment]
This problem may be occur due to tensorflow version. When i use tensorflow only 1.12.0 this properly work , not work with 1.13 or another i think.

**Comment by wrs666** [comment]
I met the exactly same problem recently, and I found this is because the type of member of filter_shape( w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init) ) is wrong. Just turn the 'float' element to 'int', the problem would be fixed. The specific modifications are as follows:

semantic_segmentation_zoo\cnn_basenet.py (about line 50 ~ 60)

            if isinstance(kernel_size, list):
                filter_shape = [kernel_size[0], kernel_size[1]] + [in_channel / split, out_channel]
            else:
                filter_shape = [kernel_size, kernel_size] + [in_channel / split, out_channel]
                print(type(in_channel / split))

change it to
            if isinstance(kernel_size, list):
                filter_shape = [kernel_size[0], kernel_size[1]] + [int(in_channel / split), out_channel]
            else:
                filter_shape = [kernel_size, kernel_size] + [int(in_channel / split), out_channel]
                print(type(in_channel / split))

**Comment by wrs666** [comment]
I met the exactly same problem recently, and I found this is because the type of member of filter_shape( w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init) ) is wrong. Just turn the 'float' element to 'int', the problem would be fixed. The specific modifications are as follows:

semantic_segmentation_zoo\cnn_basenet.py (about line 50 ~ 60)

        if isinstance(kernel_size, list):
            filter_shape = [kernel_size[0], kernel_size[1]] + [in_channel / split, out_channel]
        else:
            filter_shape = [kernel_size, kernel_size] + [in_channel / split, out_channel]
            print(type(in_channel / split))
change it to
I met the exactly same problem recently, and I found this is because the type of member of filter_shape( w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init) ) is wrong. Just turn the 'float' element to 'int', the problem would be fixed. The specific modifications are as follows:

semantic_segmentation_zoo\cnn_basenet.py (about line 50 ~ 60)

        if isinstance(kernel_size, list):
            filter_shape = [kernel_size[0], kernel_size[1]] + [in_channel / split, out_channel]
        else:
            filter_shape = [kernel_size, kernel_size] + [in_channel / split, out_channel]
            print(type(in_channel / split))

change it to

        if isinstance(kernel_size, list):
            filter_shape = [kernel_size[0], kernel_size[1]] + [int(in_channel / split), out_channel]
        else:
            filter_shape = [kernel_size, kernel_size] + [int(in_channel / split), out_channel]
            print(type(in_channel / split))

**Comment by wrs666** [comment]
I met the exactly same problem recently, and I found this is because the type of member of filter_shape( w = tf.compat.v1.get_variable('W', filter_shape, initializer=w_init) ) is wrong. Just turn the 'float' element to 'int', the problem would be fixed. The specific modifications are as follows:

semantic_segmentation_zoo\cnn_basenet.py (about line 50 ~ 60)

    if isinstance(kernel_size, list):
        filter_shape = [kernel_size[0], kernel_size[1]] + [in_channel / split, out_channel]
    else:
        filter_shape = [kernel_size, kernel_size] + [in_channel / split, out_channel]
        print(type(in_channel / split))

change it to

    if isinstance(kernel_size, list):
        filter_shape = [kernel_size[0], kernel_size[1]] + [int(in_channel / split), out_channel]
    else:
        filter_shape = [kernel_size, kernel_size] + [int(in_channel / split), out_channel]
        print(type(in_channel / split))
